#################################################
# 共通の初期設定
# ~~pathは実ファイル
# ~~dir はフォルダ
# #{root_dir}は../. の絶対パスに置換されます
#################################################

loggers:
  basic:
    logdev: "#{root_dir}/logs/batch.log"
    shift_age: 'daily'
    level: 'info'
    max_history: 7
  unexpected:
    logdev: "#{root_dir}/logs/unexpected.log"
    shift_age: 'daily'
    level: 'error'
    max_history: 90

slacks:
  common:
    channel: '#alert_info'
    level: 'info'
    token: ''
  error:
    channel: '#alert_error'
    level: 'error'
    token: ''
