#################################################
# 共通の初期設定
# ~~pathは実ファイル
# ~~dir はフォルダ
# #{root_dir}は../. の絶対パスに置換されます
#################################################

# slacks アプリの基本通知先
# stdoutは標準出力, basicは基本のlog, unexpectedはエラーを貯める用
# .media.はbatchのprefixにて置換されます。
loggers:
  stdout:
    logdev: "stdout"
    level: 'info'
  basic:
    logdev: "#{root_dir}/logs/batch.sub.log"
    shift_age: 'daily'
    level: 'info'
    max_history: 7
  unexpected:
    logdev: "#{root_dir}/logs/unexpected.sub.log"
    shift_age: 'daily'
    level: 'error'
    max_history: 90

# slacks アプリの基本通知先
# alertはエラー用 logは基本ログの通知先
slacks:
  common:
    channel: '#alert_info'
    level: 'info'
    token: ''
  error:
    channel: '#alert_error'
    level: 'error'
    token: ''

ruizu:
  kintai:
    url: 'http://localhost'
    company_code: '0'
    employee_code: '0'
    password: 'password'
